on:
  schedule:
    # 日本時間 10:00
    - cron: "0 1 * * 1-5"

    # 日本時間 11:00
    - cron: "0 2 * * 1-5"

    # 日本時間 13:00
    - cron: "0 4 * * 1-5"

    # 日本時間 14:30
    - cron: "30 5 * * 1-5"

    # 日本時間 15:45
    - cron: "45 6 * * 1-5"

  workflow_dispatch: